### ISSUE TITLE
用 Vim 编辑 Markdown 时直接粘贴图片 — 文浩

### ISSUE THREAD

**Issue by wenhaoclub** [wenhaoclub/blog-comments#2]
https://wenhaoclub.github.io//2020/05/04/paste-image-in-vim/ 

 我习惯使用 Vim 编辑 Markdown 文件，一直存在一个痛点就是粘贴图片很不方便。

**Comment by wenhaoclub** [comment]
hello world

**Comment by wenhaofree** [comment]
Long live the coding

**Comment by wenhaoclub** [comment]
> Long live the coding

Yes, Me too
